# This is a basic workflow to help you get started with Actions

name: Deploy React test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Run Job'
        required: true
        default: 'build_deploy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Npm Install Package
        run: npm install
        
      - name: Test & Code Coverage
        run: npm test -- --coverage
      
      - name: Upload Code Coverage
        uses: codevov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
      
      - name: Build Package
        env:
          CI: false
        run: npm run serve
